### PR TITLE
115 - Setting up of arduino_web_server.py on Ubuntu 18.04x64

### LINKED ISSUE #115: Setting up arduino_web_server.py on Ubuntu 18.04
There is no detailed instructions on how to run `python arduino_web_server.py` on GNU/Linux. That said, I am opening this issue to, at least, provide some instructions for setting it up on Ubuntu 18.04x64.

### PR DESCRIPTION
**Pull request by mxochicale**
Resolves https://github.com/BlocklyDuino/BlocklyDuino/issues/115

### CODE REVIEW

**Comment by SebCanet** [comment]
Hi,
I have a pb with your pull request because it needs Conda installation, and the idea of this python script is to use embedded Python, the lightest solution possible.
Could you please change this?
Thanks.

**Comment by mxochicale** [comment]
Hi,

Sure will take out conda installation instructions and add general descriptions. BTW, what do you mean by embedded python? Is it the default python installation in Ubuntu 18.04?

Thanks

**Comment by SebCanet** [comment]
Yes, the default Python installation in Ubuntu, the version, v2 ou V3, does not matter.

**Comment by mxochicale** [comment]
Hi @SebCanet have it a look to the latest commit.

**Pull request merged**
