### PR TITLE
Multiple changes, details inside.

### PR DESCRIPTION
**Pull request by stevoleeto**
I have updated a new fork with changes I have made locally over the past few months.
These blocks are focused on support for parts that come in traditional "beginners" kits.

+ while loop block: Adds a while loop block to the "control" section.
+ Serial Print fix: A serial print now prints to the next line, instead of tabbed to the side.
+ Stepper Motor: Adds three new blocks for Stepper Motors. Including setup, set speed, and move # of steps.
+ LCD support: Adds three new blocks for LCD screens that come in most kits, supports 4 digital data pins. Including setup, print, and clear.
+ Shift Register Support: Adds two new blocks, shift in and shift out.

### CODE REVIEW

**Comment by gasolin** [comment]
Could you pick some common functions(ex loop) to a single PR so we can merge them into blocklyduino

**Comment by stevoleeto** [comment]
What's the best way to do that @gasolin? Create a branch for each feature?

**Comment by gasolin** [comment]
Yes, if you think that change is worth intrgrate to blocklyduino

**Comment by stevoleeto** [comment]
I've been teaching Arduino through various programs and I believe the while loop, serial print fix, and LCD support would be useful to most people. The stepper motor / shift register blocks are cool... but would most likely never be used by the average user.

So if I make a branch with the while loop, serial print fix, and LCD support... think it'd be good?

**Comment by gasolin** [comment]
Sounds good, thanks for sharing your experience:)

**Comment by stevoleeto** [comment]
@gasolin Thank you for getting this wonderful project started! I went ahead and created a new PR. I look forward to working with you on more changes!

**Pull request closed without merging**
